### ISSUE TITLE
Missing package.json file in /dist theme

### ISSUE THREAD

**Issue by sumnermic** [mnyorba/generator-npm-wp-s-theme#31]
Hello,
There seem to be no `package.json` file from which to build the theme out of?
May I ask if the dist file is not meant to be re-developed in the future, or if there is a way to set it for re-development?

Kind regards,

**Comment by mnyorba** [comment]
Command `yo npm-wp-s-theme` do it download theme and create  `package.json`.
For re-developer theme you need SASS catalog with files, so the directory dist use only the output "clear" css and required php files theme.

**Comment by sumnermic** [comment]
Hi @mnyorba, Okay thank you I was wondering about the re-development theme. But looks like it is okay as long as we save the `package.json` in our git repo. Thank you! 👍
